version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - echo Pre_build started on `date`
      #...
      - echo Pre_build completed on `date`
  build:
    commands:
      - echo Build started on `date`
      #...
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Post_build started on `date`
      - sam package --debug --s3-bucket alinr-bucket --template-file template.yaml --output-template-file packagedTemplate.yaml
      - echo Post_build completed on `date`
artifacts:
  files:
    - packagedTemplate.yaml
