version = 0.1
[default.deploy.parameters]
stack_name = "lambda-sam"
resolve_s3 = true
s3_prefix = "lambda-sam"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "user1"
disable_rollback = true
